config/routes.rb
Rails.application.routes.draw do
  get 'prospects/list'
  get 'prospects/selected'
  get 'prospects/custcode'
  get 'prospects/chosen'
  get 'prospects/inactive'
  get 'prospects/customer'
  get 'prospects/search'
  get 'prospects/find'
  resources :prospects do
    resources :prospect_calls, except: [:index, :show]
  end
  devise_for :user2s, controllers: { registrations: "user2s/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'prospects#index'
end

app/models/prospect_call.rb
class ProspectCall < ApplicationRecord
  belongs_to :prospect, :foreign_key => "prospect_id"
end

app/controllers/prospect_calls_controller.rb
class ProspectCallsController < ApplicationController
  before_action :set_prospect
  before_action :set_prospect_call, except: [:new, :create]

  def new
    @prospect_call = ProspectCall.new
  end

  def edit
  end

  def create
    @prospect_call = Prospect_calls.new(prospect_call_params)
    @prospect_call.save
    render action: 'show', status: :created, location:@prospect
  end

  def update
    @prospect_call.update(prospect_call_params)
  end

  def destroy
    @prospect_call.destroy
    redirect_to @prospect
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:prospect_id])
    end
    def set_prospect_call
      @prospect_call = ProspectCall.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_call_params
      params.require(:prospect_call).permit(:prospect_id, :who, :outcome, :call_date)
    end
end

app/helpers/prospect_calls_helper.rb
module ProspectCallsHelper
end

app/views/prospect_calls/_form.html.erb
<%= form_for (@prospect, @prospect_call) do |f| %>
  <table>
    <thead>
      <tr>
        <th> <%= f.label :who, 'Contact' %> </th>
        <th> <%= f.label :outcome %> </th>
        <th> <%= f.label :call_date %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= f.text_field :who %> </td>
        <td> <%= f.text_field :outcome %> </td>
        <td> <%= f.date_field :call_date %> </td>
      </tr>
    </tbody>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prospect_calls/edit.html.erb
<h1>Editing Prospect Call</h1>

<%= render 'form', prospect_call: @prospect_call %>
<%= link_to 'Back', edit_prospect_path(@prospect) %>

app/views/prospect_calls/new.html.erb
<h1>New Prospect Call</h1>

<%= render 'form', prospect_call: @prospect_call %>

<%= link_to 'Back', prospect_calls_path %>