config/routes.rb
Rails.application.routes.draw do
  get 'prospects/list'
  get 'prospects/selected'
  get 'prospects/custcode'
  get 'prospects/chosen'
  get 'prospects/inactive'
  get 'prospects/customer'
  get 'prospects/search'
  get 'prospects/find'
  resources :prospects do
    resources :prospect_calls, except: [:index, :show]
  end
  devise_for :user2s, controllers: { registrations: "user2s/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'prospects#index'
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  has_many :prospect_calls, inverse_of: :prospect, :dependent => :destroy
  accepts_nested_attributes_for :prospect_calls, reject_if: proc { |attributes| attributes['who'].blank? }
  validates_presence_of :name
  validates_presence_of :zip
  validate :zip_code

  def self.get_orders
    all.each do |p|
      if !p.customer_id.blank?
        # active prospect with a customer code
        if p.ship_to.blank? || p.ship_to == p.customer_id
          sales = DartSalesPricingCurrent.where(cust_code: p.customer_id).where("sale_date >= ?", 8.weeks.ago).where("sales_dol > ?", 0).uniq{|s| s.order_numb}.take(3)
        else
          sales = DartSalesPricingCurrent.where(shipto_code: p.ship_to).where("sale_date >= ?", 8.weeks.ago).where("sales_dol > ?", 0).uniq{|s| s.order_numb}.take(3)
        end
        if sales && sales.length == 3
          # this customer is no longer a prospect so set it to inactive
          p.status = true
          p.customer = true
          p.save
        end
      end
    end
  end

  def zip_code
    if zip.present?
      a = Geocode.where(["zip = ?", zip])
      if a.length == 0
        errors.add(:zip, " code invalid")
      end
    end
  end

end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]
  before_action :set_first_and_last, only: [:show, :edit]
  before_action :set_user_and_manager
  before_action :build_rep_list, only: [:index]
  before_action :build_inactive_rep_list, only: [:inactive]
  before_action :build_customer_list, only: [:customer]

  # GET /prospects
  def index
  end

  # GET /prospects/1
  def show
  end

  # GET /prospects/new
  def new
    @new = true
    @first = ' '
    @last = ' '
    @required_date = Time.current.strftime('%Y-%m-%d')
    if $house_account
      #  fill in as much prospect information as possible for a house account
      o = Orderfrom.find_by(bus_name: $name)
      @prospect = Prospect.new(customer_id: o.cust_code, zip: o.zip, ship_to: o.ship_to, source: "HOUSE ACCOUNT")
    else
      @prospect = Prospect.new
    end
    @prospect.prospect_calls.build call_date: @required_date
  end

  # GET /prospects/1/edit
  def edit
    @new = false
    $rep = @prospect.rep
    $name = @prospect.name
    @required_date = Time.current.strftime('%Y-%m-%d')
    @prospect.prospect_calls.build call_date: @required_date
    # calls = @prospect.prospect_calls.all
    # @prospect_calls = calls.sort_by { |call| [call.call_date] }
  end

  # POST /prospects
  def create
    pp = prospect_params
    if !pp[:customer_id].blank? && pp[:ship_to].blank?
      pp[:ship_to] = pp[:customer_id]
    end
    pp[:customer] = false
    @prospect = Prospect.new(pp)
    @prospect.active_date = Date.today
    @prospect.name.upcase!
    @prospect.customer = false
    if !@prospect.zip.blank?
      a = Geocode.where(["zip = ?", @prospect.zip])
      if a.length > 0
        z = a[a.length-1]
        @prospect.city = z.city_name
        @prospect.state = z.state_name
      end
    end
    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /prospects/1
  def update
    pp = prospect_params
    pp[:name].upcase!
    if pp[:rep] != $rep
      # rep has changed so store the previous rep
      pp[:prev_rep] = $rep
      pp[:rep_date] = Date.today
    end
    if pp[:status] == '0' && @prospect.status
      # prospect has changed from inactive to active so store todays date
      pp[:active_date] = Date.today
    end
    if !pp[:zip].blank?
      a = Geocode.where(["zip = ?", pp[:zip]])
      if a.length > 0
        z = a[a.length-1]
        pp[:city] = z.city_name
        pp[:state] = z.state_name
      end
    end
    if !pp[:customer_id].blank? && pp[:ship_to].blank?
      pp[:ship_to] = pp[:customer_id]
    end
    respond_to do |format|
      if @prospect.update(pp)

        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_inactive_path, notice: 'Prospect was successfully deleted.' }
    end
  end

  def inactive
  end

  def list
    if !$prospect_reps
      # first time in
      @rep = []
      rep = []
      temprep = []
      reps = User2.all
      reps.each do |r|
        if r.manager_id != 'MAINT' && r.email != 'admin'
          temprep.push(r.email.upcase)
        end
      end

      rep = temprep.sort
      $prospect_rep = rep[0]
      i = 1
      @selected_rep = 0
      rep.each do |c|
        select_item = []
        select_item.push(c)
        select_item.push(i)
        @rep.push(select_item)
        if c == $prospect_rep
          @selected_rep = i
        end
        i += 1
      end
      $prospect_reps = @rep
      prospects = Prospect.where(rep: $prospect_rep).to_a
      @name = []
      tempname = []
      prospects.each do |p|
        if !p.name.blank?
          tempname.push(p.name)
        end
      end
      @name = tempname.sort
      $prospect_names = @name
    else
      @selected_rep = 0
      $prospect_reps.each do |p|
        if p[0] == $prospect_rep
          @selected_rep = p[1]
        end
      end
      @rep = $prospect_reps
      @name = $prospect_names
    end

  end

  def selected
    reps = $prospect_reps
    reps.each do |c|
      select_item = []
      select_item = c
      if params[:prospect_rep] == select_item[1].to_s
        $prospect_rep = select_item[0]
        break
      end
    end
    prospects = Prospect.where(rep: $prospect_rep).to_a
    @name = []
    tempname = []
    prospects.each do |p|
      if !p.name.blank?
        tempname.push(p.name)
      end
    end
    @name = tempname.sort
    $prospect_names = @name
    redirect_to action: "list"
  end

  def custcode
    prospect = Prospect.find_by name: params[:prospect_name]
    if prospect
      prospect.customer_id = params[:prospect_code]
      prospect.save
    end
    redirect_to action: "index"
  end

  def chosen
    $name = params[:prospect_name]
    $rep = params[:rep]
    prospect = Prospect.find_by name: params[:prospect_name].upcase
    if prospect
      redirect_to prospect
    else
      redirect_to action: "index", notice: 'Prospect was not found.'
    end
  end

  def find
    $house_account = false
    prospect = Prospect.find_by name: params[:name].upcase
    if prospect
      if prospect.status
        redirect_to prospects_search_path, notice: 'Prospect inactive, contact manager.'
      else
        redirect_to prospects_search_path, notice: 'Prospect already allocated.'
      end
    else
      o = Orderfrom.where(bus_name: params[:name].upcase)
      if o && o.length > 0
        orderfrom = o.first
        if !orderfrom.acct_manager.blank?
          if orderfrom.acct_manager[0,2] == 'HO' || orderfrom.acct_manager[0,2] == 'DA'
            if @manager
              $house_account = true
              $name = orderfrom.bus_name
              redirect_to new_prospect_path, notice: 'Prospect is a House Account.'
            else
              redirect_to prospects_search_path, notice: 'Prospect is a House Account, contact manager.'
            end
          else
            redirect_to prospects_search_path, notice: 'Prospect is already an account.'
          end
        else
          redirect_to prospects_search_path, notice: 'Prospect is already an account.'
        end
      else
        $name = params[:name].upcase
        redirect_to action: "new"
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
      session[:prospect_id] = @prospect_id
    end

    def set_user_and_manager
      @method = ['CALL', 'EMAIL', 'IN PERSON', 'SOCIAL MEDIA', 'TEXT']
      @outcome = ['CONTACT NOT AVAILABLE', 'CALL BACK REQUESTED', 'CREDIT APP SENT', 'INFORMATION REQUESTED', 'LEFT MESSAGE', 'MEETING SCHEDULED', 'NO INTEREST', 'ORDER']
      @source = ['CHEF REFERRAL', 'COLD CALL', 'EVENT', 'HOUSE ACCOUNT', 'NEW OPENING', 'PHONE CALL', 'SOCIAL MEDIA', 'WEBSITE LEADS', 'LOADED']
      @user = current_user2.email.upcase
      @mngr = current_user2.manager_id.upcase
      if current_user2.manager_id.upcase == 'ISR'
        @user_isr = @user
        @user = 'ADMIN'
      end
      @manager = false
      if @user == 'ADMIN' || @mngr == @user
        @manager = true
      end
    end

    def set_first_and_last
      calls = @prospect.prospect_calls.all
      now = Date.today
      @first = now
      @last = now - 10000
      calls.each do |c|
        if !c.call_date
          c.call_date = now
          c.save
        end
        if c.call_date < @first
          @first = c.call_date
        end
        if c.call_date > @last
          @last = c.call_date
        end
      end
    end

    def build_rep_list
    # Set up the prospect list for the signed in rep or all prospects for an admin
      if @user == 'ADMIN'
        @reps = User2.all
        # see all the prospects
        @prospects = Prospect.where(status: false).to_a
      elsif @mngr == @user
        # a manager should see all the prospects of their reps
        @reps = User2.where(manager_id: @mngr)
        @prospects = []
        @reps.each do |r|
          rep = r.email.upcase
          prospects = Prospect.where(rep: rep).where(status: false).to_a
          @prospects = @prospects + prospects
        end
      else
        # a rep should only see there own prospects
        @prospects = Prospect.where(rep: @user).where(status: false).to_a
      end
      @first_call = []
      @first_unformatted = []
      @last_call = []
      @prospects.each do |p|
        # need to find the first, second, third and last call date, if they exist, for each prospect by looking at the calls
        # collect all the call_date fields, then sort them
        if p.prospect_calls.length == 0
          # no call data so set everything to spaces
          @first_call.push(' ')
          @first_unformatted.push(' ')
          @last_call.push(' ')
        else
          tempcalls = []
          if p.prospect_calls.length == 1
            # only one call
            @first_call.push(p.prospect_calls.first.call_date.strftime("%Y %m %d"))
            @first_unformatted.push(p.prospect_calls.first.call_date)
            @last_call.push(p.prospect_calls.first.call_date.strftime("%Y %m %d"))
          else
            p.prospect_calls.each do |c|
              tempcalls.push(c.call_date)
            end
            tempcalls.sort!
            if p.prospect_calls.length == 2
              @first_call.push(tempcalls[0].strftime("%Y %m %d"))
              @first_unformatted.push(tempcalls[0])
              @last_call.push(tempcalls[1].strftime("%Y %m %d"))
            else
              @first_call.push(tempcalls[0].strftime("%Y %m %d"))
              @first_unformatted.push(tempcalls[0])

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/prospects/_form.html.erb
<%= form_with(model: prospect, local: true) do |form| %>
  <% if prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% prospect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead>
      <tr>
        <th> <%= form.label :rep %> </th>
        <th> <%= form.label :name, "Business name" %> </th>
        <th> <%= form.label :zip %> </th>
        <th> <%= form.label :source %> </th>
        <th> <%= form.label :new_opening, "New opening?" %> </th>
        <th> <%= form.label :compass, "Compass?" %> </th>
    </thead>
    <tbody>
      <tr>
        <% if @new %>
          <% if @manager %>
            <% if @user == 'ADMIN' %>
              <td> <%= form.text_field :rep, value: @user_isr %> </td>
            <% else %>
              <td> <%= form.text_field :rep, :value => @user, id: :prospect_rep %> </td>
            <% end %>
          <% else %>
            <td> <%= form.text_field :rep, :value => @user, readonly: true, id: :prospect_rep %> </td>
          <% end %>
        <% else %>
          <% if @manager %>
            <td> <%= form.text_field :rep, id: :prospect_rep %> </td>
          <% else %>
            <td> <%= form.text_field :rep, readonly: true, id: :prospect_rep %> </td>
          <% end %>
        <% end %>
        <% if @new %>
          <td> <%= form.text_field :name, :value => $name, id: :prospect_name %> </td>
        <% else %>
          <td> <%= form.text_field :name, id: :prospect_name %> </td>
        <% end %>
        <td> <%= form.text_field :zip, size: "5", id: :prospect_zip %> </td>
        <td> <%= form.select :source, @source, {}, {:value => params[:source], id: :prospect_source} %> </td>
        <td> <%= form.check_box :new_opening, id: :prospect_new_opening %> </td>
        <td> <%= form.check_box :compass, id: :prospect_compass %> </td>
      </tr>
    </tbody>
  </table>

  <table>
    <thead>
      <tr>
        <th> <%= form.label :activities %> </th>
        <th> <%= form.label :first_activity %> </th>
        <th> <%= form.label :last_activity %> </th>
        <th> <%= form.label :customer_id, "Customer code" %> </th>
        <th> <%= form.label :ship_to %> </th>
        <th> <%= form.label :status, "Inactive?" %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= @prospect.prospect_calls.count %> </td>
        <% if @first == ' ' %>
          <td></td>
          <td></td>
        <% else %>
          <td> <%= display_date(@first) %> </td>
          <% if @last == ' ' %>
            <td></td>
          <% else %>
            <td> <%= display_date(@last) %> </td>
          <% end %>
        <% end %>
        <td> <%= form.text_field :customer_id, id: :prospect_customer_id %> </td>
        <td> <%= form.text_field :ship_to, id: :prospect_ship_to %> </td>
        <% if @manager %>
          <td> <%= form.check_box :status, id: :prospect_status %> </td>
        <% else %>
          <td> <%= form.check_box :status, readonly: true, id: :prospect_status %> </td>
        <% end %>
      </tr>
    </tbody>
  </table>

  <h3>Activities</h3>
  <% i = 1 %>
  <%= form.fields_for :prospect_calls, form.object.prospect_calls.sort_by(&:call_date) do |p| %>

  <table>
    <% if i == 1 %>
      <thead>
        <tr>
          <th> <%= p.label :who, 'Contact' %> </th>
          <th> <%= p.label :call_date, 'Activity date' %> </th>
          <th> <%= p.label :method %> </th>
          <th> <%= p.label :subject, 'Notes' %> </th>
          <th> <%= p.label :outcome %> </th>
        </tr>
      </thead>
      <% i = 2 %>
    <% end %>
    <tbody>
        <tr>
          <td> <%= p.text_field :who, size: "15" %> </td>
          <% if @new %>
            <td> <%= p.date_field :call_date, max: Date.today, min: Date.today - 10 %> </td>
          <% else %>
            <!-- Pierre needed to update prospects that contained activities with invalid dates -->
            <td> <%= p.date_field :call_date, max: Date.today %> </td>
          <% end %>
          <td> <%= p.select :method, @method %> </td>
          <td> <%= p.text_area :subject, size: "20x4" %> </td>
          <td> <%= p.select :outcome, @outcome %> </td>
        </tr>
    </tbody>
  </table>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prospects/customer.html.erb
<p id="notice"><%= notice %></p>
<h3>Prospects To Customers</h3>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <% if @user == "admin" || @user == @mngr %>
        <th>Rep</th>
      <% end %>
      <th>Custcode</th>
      <th>Name</th>
      <th>Activities</th>
      <th>Last activity</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <% if @user == "admin" || @user == @mngr %>
          <td><%= prospect.rep %></td>
        <% end %>
        <td><%= prospect.customer_id %></td>
        <td><%= prospect.name %></td>
        <td><%= prospect.prospect_calls.count %></td>
        <td><%= last_call(prospect.id) %></td>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Delete', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %>

app/views/prospects/edit.html.erb
<h3>Editing Prospect</h3>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Show', @prospect %>
<%= link_to 'List', prospects_path %>

app/views/prospects/inactive.html.erb
<p id="notice"><%= notice %></p>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <% if @user == "admin" || @user == @mngr %>
        <th>Rep</th>
      <% end %>
      <th>Custcode</th>
      <th>Name</th>
      <th>Calls</th>
      <th>1st call</th>
      <th>2nd call</th>
      <th>3rd call</th>
      <th>Last call</th>
      <% if @user == "admin" || @user == @mngr %>
        <th>Inactive</th>
      <% end %>
      <th>Show</th>
      <th>Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <% if @user == "admin" || @user == @mngr %>
          <td><%= prospect.rep %></td>
        <% end %>
        <td><%= prospect.customer_id %></td>
        <td><%= prospect.name %></td>
        <td><%= prospect.prospect_calls.count %></td>
        <% if prospect.prospect_calls.present? %>
          <% if prospect.prospect_calls.first.present? %>
            <td><%= display_date(prospect.prospect_calls.first.call_date) %></td>
          <% else %>
            <td></td>
          <% end %>
          <% if prospect.prospect_calls.second.present? %>
            <td><%= display_date(prospect.prospect_calls.second.call_date) %></td>
          <% else %>
            <td></td>
          <% end %>
          <% if prospect.prospect_calls.third.present? %>
            <td><%= display_date(prospect.prospect_calls.third.call_date) %></td>
          <% else %>
            <td></td>
          <% end %>
          <% if prospect.prospect_calls.last.present? %>
            <td><%= display_date(prospect.prospect_calls.last.call_date) %></td>
          <% else %>
            <td></td>
          <% end %>
        <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        <% end %>
        <% if @user == "admin" || @user == @mngr %>
          <td> <%= human_boolean(prospect.status) %> </td>
        <% end %>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %>

app/views/prospects/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Prospects Summary</h3>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th>Customer</th>
      <th>Name</th>
      <th>City/State</th>
      <% if @user == "admin" || @user == @mngr %>
        <th>Rep</th>
      <% end %>
      <th>Activities</th>
      <th>1st activity</th>
      <th>Last activity</th>
      <th>Days active</th>
      <th>Show</th>
      <th>Edit</th>
    </tr>
  </thead>

  <tbody>
    <% i = 0 %>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.customer_id %></td>
        <td><%= prospect.name %></td>
        <td><%= city_state(prospect) %></td>
        <% if @user == "admin" || @user == @mngr %>
          <td><%= prospect.rep %></td>
        <% end %>
        <td><%= prospect.prospect_calls.count %></td>
        <td><%= @first_call[i] %></td>
        <td><%= @last_call[i] %></td>
        <% if prospect.active_date.blank? %>
          <% if @first_call[i].blank? %>
            <td> UNKNOWN </td>
          <% else %>
            <td><%= days_active(@first_unformatted[i]) %></td>
          <% end %>
        <% else  %>
          <td><%= days_active(prospect.active_date) %></td>
        <% end %>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
      </tr>
      <% i += 1 %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', prospects_search_path %>

app/views/prospects/index_save.html.erb
<p id="notice"><%= notice %></p>

<% if !@name %>
  <h3>No prospects</h3>
<% else %>
  <%= form_with url: prospects_chosen_path, local: true, method: 'get' do |f| %>
    <%= f.label(:rep, 'Rep:') %>
    <%= f.select :rep, @rep, {include_blank: true, selected: $rep}, {:value => params[:rep], :id => "rep", :onChange=> ('set_name()')} %>
    <%= f.label:prospect_name, 'Name:' %>
    <%= f.select :prospect_name, @name, {selected: $name}, {:value => params[:name], :id => "name"} %>
    <%= f.submit "Select" %>
  <% end %>
  <p id= "reps" hidden> <%= $reps %> </p>
  <p id= "names" hidden> <%= $names %> </p>
<% end %>

app/views/prospects/list.html.erb
<p id="notice"><%= notice %></p>

<h2>Enter Customer Code</h2>
<% if @mngr == ' ' %>
  <%= form_with url: prospects_selected_path, local: true, method: 'get' do |f| %>
    <%= f.label:prospect_rep, 'Rep:' %>
    <%= f.select(:prospect_rep, options_for_select(@rep, @selected_rep)) %>
    <%= f.submit "Change" %>
  <% end %>
<% end %>

<br>

<% if !@name %>
  <h3>No prospects</h3>
<% else %>
  <%= form_with url: prospects_custcode_path, local: true, method: 'get' do |f| %>
    <%= f.label:prospect_name, 'Name:' %>
    <%= f.select(:prospect_name, options_for_select(@name)) %>
    <%= f.label(:prospect_code, "Customer code:") %>
    <%= f.text_field :prospect_code %>
    <%= f.submit "Submit" %>
  <% end %>
<% end %>

app/views/prospects/new.html.erb
<p id="notice"><%= notice %></p>

<h3>New Prospect</h3>

<%= render 'form', prospect: @prospect %>

<%= link_to 'List', prospects_path %>

app/views/prospects/search.html.erb
<p id="notice"><%= notice %></p>

<h3>Prospect Search</h3>

<%= form_with url: prospects_find_path, local: true, method: 'get' do |f| %>
  <%= f.label:prospect_name, 'Customer Name:' %>
  <%= f.text_field :name, id: :prospect_name %>
  <%= f.submit "Submit" %>
<% end %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Showing Prospect</h3>

<table>
  <thead>
    <tr>
      <th> Rep </th>
      <th> Business name </th>
      <th> Activities </th>
      <th> First activity </th>
      <th> Last activity </th>
      <th> Customer </th>
      <th> Ship to </th>
      <th> Inactive? </th>
      <th> New opening? </th>
      <th> Compass? </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @prospect.rep %> </td>
      <td> <%= @prospect.name %> </td>
      <td> <%= @prospect.prospect_calls.count %> </td>
      <% if @first == ' ' %>
        <td></td>
        <td></td>
      <% else %>
        <td> <%= display_date(@first) %> </td>
        <% if @last == ' ' %>
          <td></td>
        <% else %>
          <td> <%= display_date(@last) %> </td>
        <% end %>
      <% end %>
      <td> <%= @prospect.customer_id %> </td>
      <td> <%= @prospect.ship_to %> </td>
      <td> <%= human_boolean(@prospect.status) %> </td>
      <td> <%= human_boolean(@prospect.new_opening) %> </td>
      <td> <%= human_boolean(@prospect.compass) %> </td>
    </tr>
  </tbody>
</table>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th hidden> ID </th>
      <th> Contact </th>
      <th> Call date </th>
      <th> Method </th>
      <th> Notes </th>
      <th> Outcome </th>
      <% if @manager %>
      <th> Created at </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @prospect.prospect_calls.each do |c| %>
    <tr>
      <td hidden> <%= c.id %> </td>
      <td> <%= c.who %> </td>
      <td> <%= display_date(c.call_date) %> </td>
      <td> <%= c.method %> </td>
      <% if c.subject %>
        <td> <%= word_wrap(c.subject, line_width: 20) %> </td>
      <% end %>
      <td> <%= c.outcome %> </td>
      <% if @manager %>
      <td> <%= c.created_at %> </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<% if @manager || @user == @prospect.rep %>
  <%= link_to 'Edit', edit_prospect_path(@prospect) %>
<% end %>
<%= link_to 'List', prospects_path %>