config/routes.rb
Rails.application.routes.draw do
  get 'prospects/list'
  get 'prospects/selected'
  get 'prospects/custcode'
  get 'prospects/chosen'
  get 'prospects/inactive'
  get 'prospects/customer'
  get 'prospects/search'
  get 'prospects/find'
  resources :prospects do
    resources :prospect_calls, except: [:index, :show]
  end
  devise_for :user2s, controllers: { registrations: "user2s/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'prospects#index'
end

app/views/layouts/_header.html.erb
<span class="primary-logo">
</span>
<% if current_user2 %>
  <div id="navbar">
    <span><%= link_to 'Summary', prospects_path  %></span>
    <span><%= link_to 'New', '/prospects/search' %></span>
    <span><%= link_to 'Password', edit_user2_registration_path %></span>
    <span><%= link_to 'Sign out', destroy_user2_session_path, method: :delete %></span>
    <% if @manager %>
      <span><%= link_to 'Inactive', '/prospects/inactive' %></span>
      <span><%= link_to 'Customer', '/prospects/customer' %></span>
    <% end %>
    <% if current_user2.email == "admin" %>
      <span><%= link_to 'Sign up', new_user2_registration_path %></span>
    <% end %>
  </div>
<% end %>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prospects</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="global">
      <div style="position: fixed; top: 0px; width: 100%; height: 4em; background-color: white; z-index: 100;">
        <%= render 'layouts/header' %>
      </div>
      <div style="margin-top: 7.5em;">
        <%= yield %>
      </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script src="/assets/printPreview.js"></script>
    <script src="/assets/myjavascript.js"></script>
  </body>
</html>